import {iso,years,nonnegative,frozen,CoreBlocked} from './schema.js';
import {EconomicPathLedger} from './ledgers.js';
const order=['contractual','realization','tax_cost','income_receipt','consumption','routing','capacity_reservation','lot_update','death_settlement','reconciliation'];
export class EventEngine{run(state,events,{accrue,handlers}){iso(state.date);if(typeof accrue!=='function')throw new TypeError('accrual required');const sorted=events.map((e,i)=>({...e,index:i})).sort((a,b)=>a.date.localeCompare(b.date)||order.indexOf(a.type)-order.indexOf(b.type)||a.index-b.index);let s={...state},trace=[];for(const e of sorted){iso(e.date);if(e.date<s.date||!order.includes(e.type)||typeof handlers[e.type]!=='function')throw new Error('invalid event date, type or handler');s=accrue(s,e.date);s=handlers[e.type](s,e);s={...s,date:e.date};trace.push(frozen({date:e.date,type:e.type,index:e.index}))}return frozen({state:frozen(s),trace:frozen(trace)})}}
export class ContractAdapterRegistry{#contracts=new Map();register(id,adapter){if(typeof adapter.getCashflowSchedule!=='function')throw new TypeError('contract adapter required');this.#contracts.set(id,adapter)}schedule(id,context){const c=this.#contracts.get(id);if(!c)throw new CoreBlocked('contract missing');if(!context.commencementDate)throw new CoreBlocked('guarantee commencement missing');const rows=c.getCashflowSchedule(context);if(!Array.isArray(rows))throw new CoreBlocked('contract schedule missing');return frozen(rows.map(x=>{iso(x.date);for(const n of ['baseSurvivorPension','guaranteeTopUp','tax','cost'])nonnegative(x[n],n);if(!x.ruleId)throw new CoreBlocked('contract rule id missing');return frozen({...x})}))}}
export class BaselineScenarioResult{
 constructor({capitalAtMemberDeath,valuationDate,scenarioId='NO_PLANNING'}){nonnegative(capitalAtMemberDeath,'baseline capital');iso(valuationDate);if(typeof scenarioId!=='string'||!scenarioId)throw new TypeError('baseline scenario ID required');this.scenarioKind='INDEPENDENT_COMPARISON';this.scenarioId=scenarioId;this.valuationDate=valuationDate;this.capitalAtMemberDeath=capitalAtMemberDeath;Object.freeze(this)}
}
export class MemberDeathSettlement{settle(input){
 const allowed=['memberDeathDate','spouseDeathDate','pathLedger','lotLedger','allocations','immediatePaths','continuingPathIds','rights','contractRegistry','baselineScenario'];
 if(!input||typeof input!=='object'||Object.keys(input).some(k=>!allowed.includes(k)))throw new TypeError('MemberDeathSettlement: unsupported input; independentCapital and baselineCapital scalars forbidden');
 const {memberDeathDate,spouseDeathDate,pathLedger,lotLedger=null,allocations=[],immediatePaths=[],continuingPathIds=[],rights=[],contractRegistry,baselineScenario=null}=input;
 iso(memberDeathDate);iso(spouseDeathDate);if(spouseDeathDate<memberDeathDate)throw new CoreBlocked('spouse predeceases member: separate branch required');if(!(pathLedger instanceof EconomicPathLedger))throw new TypeError('EconomicPathLedger required');if(!Array.isArray(allocations)||!Array.isArray(immediatePaths)||!Array.isArray(continuingPathIds)||!Array.isArray(rights)||!contractRegistry)throw new TypeError('invalid settlement collections or contract registry');if(allocations.length&&!lotLedger)throw new TypeError('LotLedger required for lot allocations');if(baselineScenario!==null&&(!(baselineScenario instanceof BaselineScenarioResult)||baselineScenario.valuationDate!==memberDeathDate))throw new TypeError('independent baseline scenario required');
 // The opening state is a clean member-death snapshot; older FinalUses require a separate dated opening normalization.
 if(pathLedger.finalUses().length)throw new CoreBlocked('member-death opening snapshot cannot contain pre-existing FinalUses');
 pathLedger.reconcile(lotLedger??undefined);
 const ids=new Set(),coveredLeaves=new Set(),finalIds=new Set();for(const a of allocations){if(!a||typeof a!=='object'||!a.lotId||ids.has(a.lotId))throw new Error('duplicate/invalid member lot allocation');ids.add(a.lotId);const lot=lotLedger.get(a.lotId);if(!lot||lot.owner!=='member'||lot.currentValue<=0)throw new Error('member lot required');if(coveredLeaves.has(lot.economicPathId))throw new Error('duplicate member path allocation');coveredLeaves.add(lot.economicPathId);for(const key of ['immediateAmount','spouseAmount','continuingAmount'])nonnegative(a[key]??0,key);if(Math.abs((a.immediateAmount??0)+(a.spouseAmount??0)+(a.continuingAmount??0)-lot.currentValue)>1e-8)throw new Error('member death allocation exceeds or strands root');if(a.immediateAmount){if(!a.finalUseId||finalIds.has(a.finalUseId))throw new Error('unique immediate final use required');finalIds.add(a.finalUseId)}if(a.spouseAmount&&lotLedger.get(`inherited:${a.lotId}`)||a.continuingAmount&&lotLedger.get(`continuing:${a.lotId}`))throw new Error('member death target lot already exists');for(const suffix of ['heirs','spouse','continuing'])if(pathLedger.get(`${lot.economicPathId}:death:${a.lotId}:${suffix}`))throw new Error('member death target path already exists')}
 for(const x of immediatePaths){if(!x?.pathId||!x.finalUseId||coveredLeaves.has(x.pathId)||finalIds.has(x.finalUseId))throw new Error('duplicate immediate path/use');coveredLeaves.add(x.pathId);finalIds.add(x.finalUseId);const p=pathLedger.get(x.pathId);if(!p||p.currentOwner!=='member'||p.currentLotId||!pathLedger.liveLeaves().some(y=>y.id===x.pathId))throw new Error('immediate path must be an unbound member-owned leaf')}
 const explicitContinuing=new Set();for(const pathId of continuingPathIds){if(explicitContinuing.has(pathId)||coveredLeaves.has(pathId)||!pathLedger.liveLeaves().some(p=>p.id===pathId))throw new Error('invalid explicit continuing path');explicitContinuing.add(pathId);coveredLeaves.add(pathId)}
 if(pathLedger.liveLeaves().some(p=>!coveredLeaves.has(p.id)))throw new Error('all continuing member-death paths must be explicit');
 const schedule=rights.flatMap(r=>contractRegistry.schedule(r.contractId,{...r,memberDeathDate,spouseDeathDate}));const inheritedLots=[],immediateFinalUses=[];
 for(const a of allocations){const result=lotLedger.allocateAtDeath(a.lotId,{immediateAmount:a.immediateAmount??0,spouseAmount:a.spouseAmount??0,continuingAmount:a.continuingAmount??0,finalUseId:a.finalUseId},memberDeathDate);if(result.spouseLot)inheritedLots.push(result.spouseLot);if(result.continuingLot)explicitContinuing.add(result.continuingLot.economicPathId);if(result.immediateUse)immediateFinalUses.push(result.immediateUse)}
 for(const x of immediatePaths){const p=pathLedger.get(x.pathId);immediateFinalUses.push(pathLedger.finalize(p.id,x.finalUseId,'heirs',memberDeathDate,p.amount,'immediate_inheritance',memberDeathDate))}
 const core=pathLedger.reconcile(lotLedger??undefined),immediateCapital=immediateFinalUses.reduce((n,u)=>n+u.amountNet,0),inheritedIds=new Set(inheritedLots.map(l=>l.economicPathId)),spouseLots=inheritedLots.reduce((n,l)=>n+l.currentValue,0),unclaimed=pathLedger.liveLeaves().filter(p=>!inheritedIds.has(p.id)&&!explicitContinuing.has(p.id));if(unclaimed.length)throw new Error('all continuing member-death paths must be explicit');const continuingPaths=pathLedger.liveLeaves().filter(p=>explicitContinuing.has(p.id)).reduce((n,p)=>n+p.amount,0),explicitSinksCosts=core.sinkTotal;
 const gap=core.rootTotal-immediateCapital-spouseLots-explicitSinksCosts-continuingPaths;if(Math.abs(gap)>1e-8||Math.abs(core.finalTotal-immediateCapital)>1e-8)throw new Error('member death lineage reconciliation failed');
 const result={memberDeathDate,immediateCapital,immediateFinalUses:frozen(immediateFinalUses),baselineScenario,transferredRights:frozen([...rights]),inheritedLots:frozen(inheritedLots),schedule:frozen(schedule),reconciliation:frozen({openingRoots:core.rootTotal,immediateFinalUses:immediateCapital,transferredSpouseLots:spouseLots,explicitSinksCosts,continuingMemberDeathPaths:continuingPaths,gap,rootToLeaf:core})};
 // Legacy comparison read remains non-enumerable; it is not a planned economic value.
 Object.defineProperty(result,'noPlanningCapital',{enumerable:false,get(){return baselineScenario?.capitalAtMemberDeath??null}});return frozen(result)
}}
const annualServiceDates=(start,end,amount)=>{const dates=[];const [y,m,d]=start.split('-').map(Number);for(let n=1;;n++){const year=y+n;const day=Math.min(d,new Date(Date.UTC(year,m,0)).getUTCDate());const date=`${year}-${String(m).padStart(2,'0')}-${String(day).padStart(2,'0')}`;if(date>end)break;dates.push({date,amount})}return dates};
export class PostDeathSpouseEngine{run({memberDeathDate,spouseDeathDate,initialSpouseWealth,annualReturn,requiredConsumption,schedule,terminalTax=0,serviceSchedule=null,pathLedger=null,openingPathId=null,lotLedger=null}){
 iso(memberDeathDate);iso(spouseDeathDate);if(spouseDeathDate<memberDeathDate)throw new CoreBlocked('spouse predeceased member');for(const [name,n] of Object.entries({initialSpouseWealth,requiredConsumption,terminalTax}))nonnegative(n,name);if(!Number.isFinite(annualReturn)||annualReturn<=-1)throw new RangeError('return invalid');if(!Array.isArray(schedule))throw new TypeError('contract schedule required');
 const paths=pathLedger??new EconomicPathLedger(),existingFinalIds=new Set(paths.finalUses().map(u=>u.id)),accounts=[];let serial=0,last=memberDeathDate,accrual=0,receipt=0,consumed=0,taxAndCost=terminalTax,rows=[];
 const total=()=>accounts.reduce((a,x)=>a+x.balance,0);
 const add=(pathId,amount,source,date,existing=false)=>{if(existing){const p=paths.get(pathId);if(!p||p.currentOwner!=='spouse'||Math.abs(p.amount-amount)>1e-8||p.finalUseId)throw new Error('opening spouse path mismatch')}else paths.open(pathId,amount,{currentOwner:'spouse',sourceEventId:`${source}:${date}`});accounts.push({pathId,balance:amount,source})};
 if(openingPathId&&!pathLedger)throw new TypeError('openingPathId requires shared ledger');if(pathLedger&&!openingPathId&&initialSpouseWealth>0)throw new TypeError('shared ledger requires openingPathId');if(openingPathId&&paths.get(openingPathId)?.currentLotId){if(!lotLedger)throw new TypeError('lotLedger required to release opening asset');const lotId=paths.get(openingPathId).currentLotId;openingPathId=lotLedger.release(lotId,`pd:released:${lotId}`,`spouse_opening:${memberDeathDate}`).id}add(openingPathId??'pd:opening',initialSpouseWealth,'initial_spouse_wealth',memberDeathDate,!!openingPathId);
 const take=(amount,category,date)=>{if(amount>total()+1e-8)throw new CoreBlocked('required spouse service or tax unfunded');let outstanding=amount;for(const a of accounts){if(outstanding<=1e-9)break;const d=Math.min(outstanding,a.balance);if(d<=0)continue;const parent=a.pathId,remaining=a.balance-d;if(remaining>0){const kept=`${parent}:keep:${serial++}`;paths.open(kept,remaining,{parentPathId:parent,currentOwner:'spouse',sourceEventId:`${category}:${date}`});a.pathId=kept}const sinkId=`${parent}:sink:${serial++}`;if(remaining>0){paths.open(sinkId,d,{parentPathId:parent,currentOwner:'spouse',sourceEventId:`${category}:${date}`})}paths.sink(remaining>0?sinkId:parent,`pd:${category}:${serial++}`,category,date,d);a.balance=remaining;outstanding-=d}if(outstanding>1e-7)throw new Error('account draw discrepancy')};
 const grow=(date)=>{const factor=Math.pow(1+annualReturn,years(last,date));if(factor>=1){let gain=0;for(const a of accounts)gain+=a.balance*(factor-1);if(gain>1e-12){add(`pd:return:${serial++}`,gain,'investment_return',date);accrual+=gain}}else{let loss=total()*(1-factor);take(loss,'investment_loss',date);accrual-=loss}last=date};
 const receipts=schedule.map((p,i)=>{iso(p.date);for(const n of ['baseSurvivorPension','guaranteeTopUp','tax','cost'])nonnegative(p[n],n);if(!p.ruleId)throw new CoreBlocked('missing contract rule ID');return {date:p.date,type:'receipt',p,i}}).filter(e=>e.date>memberDeathDate&&e.date<=spouseDeathDate);
 const service=serviceSchedule??annualServiceDates(memberDeathDate,spouseDeathDate,requiredConsumption);if(!Array.isArray(service))throw new TypeError('service schedule array required');const services=service.map((x,i)=>{iso(x.date);nonnegative(x.amount,'service amount');return {date:x.date,type:'service',amount:x.amount,i}}).filter(e=>e.date>memberDeathDate&&e.date<=spouseDeathDate);
 const events=[...receipts,...services].sort((a,b)=>a.date.localeCompare(b.date)||(a.type==='receipt'?-1:1)||a.i-b.i);
 for(const event of events){grow(event.date);if(event.type==='receipt'){const {p,i}=event,gross=p.baseSurvivorPension+p.guaranteeTopUp,cost=p.tax+p.cost;if(cost>gross)throw new Error('tax and cost exceed receipt');receipt+=gross;if(gross)add(`pd:receipt:${i}`,gross,'contract_receipt',p.date);if(cost){take(cost,'tax_and_cost',p.date);taxAndCost+=cost}rows.push(frozen({date:p.date,baseSurvivorPension:p.baseSurvivorPension,guaranteeTopUp:p.guaranteeTopUp,consumption:0,taxAndCost:cost,closingWealth:total(),ruleId:p.ruleId}))}else{if(event.amount){take(event.amount,'required_service',event.date);consumed+=event.amount}rows.push(frozen({date:event.date,service:event.amount,closingWealth:total()}))}}
 grow(spouseDeathDate);if(terminalTax>total()+1e-8)throw new Error('terminal tax exceeds wealth');if(terminalTax)take(terminalTax,'terminal_tax',spouseDeathDate);const wealth=total();const gap=initialSpouseWealth+receipt+accrual-consumed-taxAndCost-wealth;if(Math.abs(gap)>1e-7)throw new Error('post-death reconciliation failure');
 for(const a of accounts)if(a.balance>0)paths.finalize(a.pathId,`terminal:${a.pathId}`,'heirs',spouseDeathDate,a.balance,'estate',memberDeathDate);const ledgerReconciliation=paths.reconcile(lotLedger);const finalUses=paths.finalUses().filter(x=>!existingFinalIds.has(x.id));
 if(Math.abs(finalUses.reduce((s,u)=>s+u.amountNet,0)-wealth)>1e-7)throw new Error('terminal estate lineage mismatch');return frozen({memberDeathDate,spouseDeathDate,terminalEstate:wealth,rows:frozen(rows),economicPaths:frozen(accounts.map(a=>frozen({...a}))),pathLedger:paths,ledgerReconciliation,reconciliation:frozen({opening:initialSpouseWealth,receipt,accrual,consumption:consumed,taxAndCost,terminalEstate:wealth,gap}),finalUses:frozen(finalUses)})
}}
export class ScenarioValuator{value(uses,memberDeathDate,annualDiscount){iso(memberDeathDate);if(!Number.isFinite(annualDiscount)||annualDiscount<=-1)throw new RangeError('discount rate invalid');const components=uses.map(u=>{if(u.valuationDate!==memberDeathDate||u.date<memberDeathDate)throw new Error('valuation-date mismatch');const pv=u.amountNet/Math.pow(1+annualDiscount,years(memberDeathDate,u.date));return frozen({...u,pvAtMemberDeath:pv})});return frozen({valuationDate:memberDeathDate,total:components.reduce((a,c)=>a+c.pvAtMemberDeath,0),components:frozen(components)})}}