export class CoreBlocked extends Error {constructor(message){super(message);this.name='CoreBlocked';this.status='BLOCKED'}}
export const requireFields=(x,fields,label)=>{if(!x||typeof x!=='object'||Array.isArray(x))throw new TypeError(`${label}: object required`);for(const f of fields)if(x[f]===undefined||x[f]===null)throw new TypeError(`${label}: missing ${f}`);return x};
export const nonnegative=(n,label)=>{if(typeof n!=='number'||!Number.isFinite(n)||n<0)throw new RangeError(`${label}: finite nonnegative required`);return n};
export const iso=d=>{if(typeof d!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(d)||new Date(d+'T00:00:00Z').toISOString().slice(0,10)!==d)throw new TypeError(`invalid ISO date: ${d}`);return d};
export const years=(a,b)=>(Date.parse(iso(b)+'T00:00:00Z')-Date.parse(iso(a)+'T00:00:00Z'))/(365.2425*864e5);
export const frozen=x=>Object.freeze(x);
export const lotFields=['id','owner','wrapper','providerId','sourceType','contributionDate','originalPrincipal','currentValue','taxBasisNominal','taxBasisReal','taxClass','classificationStatus','deathRuleId','withdrawalRuleId','feeScheduleId','liquidityClass','economicPathId'];
export const rightFields=['id','owner','contractId','rightType','sourceAssetId','commencementDate','monthlyAmountRule','survivorPct','guaranteeMonths','recipientRules','terminationRules','ruleIds'];
export function validateLot(x){requireFields(x,lotFields,'Lot');if(!['member','spouse'].includes(x.owner)||!['pension','t190','savings_policy','taxable','cash'].includes(x.wrapper)||!['fresh_contribution','transfer','annuity_reinvestment','realization_proceeds','inherited'].includes(x.sourceType)||!['qualifying','recognized','other'].includes(x.taxClass))throw new TypeError('invalid Lot enum');iso(x.contributionDate);for(const k of ['originalPrincipal','currentValue','taxBasisNominal','taxBasisReal'])nonnegative(x[k],k);return frozen({...x})}
export function validateRight(x){requireFields(x,rightFields,'Right');iso(x.commencementDate);nonnegative(x.survivorPct,'survivorPct');nonnegative(x.guaranteeMonths,'guaranteeMonths');if(!Array.isArray(x.ruleIds))throw new TypeError('ruleIds must be array');return frozen({...x,ruleIds:frozen([...x.ruleIds])})}
export function validateCapacity(x){requireFields(x,['taxYear','capacityType','verifiedAmount','reservedAmount','sourceRuleId','legalStatus'],'Capacity');if(!Number.isInteger(x.taxYear))throw new TypeError('taxYear integer required');nonnegative(x.verifiedAmount,'verifiedAmount');nonnegative(x.reservedAmount,'reservedAmount');if(x.reservedAmount>x.verifiedAmount+1e-10)throw new RangeError('capacity overspent');return frozen({...x})}
export function validateEconomicPath(x){requireFields(x,['id','currentOwner','amount'],'EconomicPath');for(const k of ['parentPathId','sourceEventId','currentLotId','finalUseId'])if(!(k in x))throw new TypeError(`EconomicPath: missing ${k}`);if(!['member','spouse'].includes(x.currentOwner))throw new TypeError('invalid path owner');nonnegative(x.amount,'path amount');return frozen({...x})}
export function validateFinalUse(x){requireFields(x,['id','pathId','recipient','date','amountNet','category','valuationDate'],'FinalEconomicUse');iso(x.date);iso(x.valuationDate);nonnegative(x.amountNet,'amountNet');return frozen({...x})}
function deepCloneFreeze(value,seen=new WeakSet()){
 if(value===null||typeof value==='string'||typeof value==='boolean'||typeof value==='number'&&Number.isFinite(value))return value;
 if(!value||typeof value!=='object')throw new TypeError('State contains unsupported value');
 if(seen.has(value))throw new TypeError('State contains a cycle');seen.add(value);
 if(!Array.isArray(value)&&Object.getPrototypeOf(value)!==Object.prototype&&Object.getPrototypeOf(value)!==null)throw new TypeError('State requires plain data objects');
 const copy=Array.isArray(value)?[]:{};for(const key of Reflect.ownKeys(value)){if(typeof key!=='string')throw new TypeError('State symbol key unsupported');const d=Object.getOwnPropertyDescriptor(value,key);if(!('value' in d))throw new TypeError('State accessors unsupported');copy[key]=deepCloneFreeze(d.value,seen)}seen.delete(value);return frozen(copy)
}
export function validateState(x){requireFields(x,['date','memberAlive','spouseAlive','lots','rights','capacities','taxState','incomeState','requiredConsumption','finalUses'],'State');iso(x.date);if(typeof x.memberAlive!=='boolean'||typeof x.spouseAlive!=='boolean')throw new TypeError('alive booleans required');for(const k of ['lots','rights','capacities','finalUses'])if(!Array.isArray(x[k]))throw new TypeError(`${k} array required`);for(const k of ['taxState','incomeState'])if(!x[k]||typeof x[k]!=='object'||Array.isArray(x[k]))throw new TypeError(`${k} object required`);for(const l of x.lots)validateLot(l);for(const r of x.rights)validateRight(r);for(const c of x.capacities)validateCapacity(c);for(const f of x.finalUses)validateFinalUse(f);nonnegative(x.requiredConsumption,'requiredConsumption');return deepCloneFreeze(x)}